### ISSUE TITLE
Bad state: Response has no Location header for redirect

### ISSUE THREAD

**Issue by anamarielzamora** [diagnosia/flutter_aws_s3_client#3]
Bad state: Response has no Location header for redirect

Dart is requesting for headers but listObjects has no headers to add. How can i resolve this? 
My code line:
```
    ListBucketResult listBucketResult = await s3client.listObjects(prefix: "banners/", delimiter: "/");
    print(listBucketResult.toString());
```

Thanks and regards

**Comment by knaeckeKami** [comment]
Hi,
thanks for reporting this issue.

Can you provide the whole response and/or a stack trace? I'm not sure why this error would occur.

**Comment by anamarielzamora** [comment]
```
Error messagge "Response has no Location header for redirect"
```

And stackTrace
```
#0      _HttpClientResponse.redirect (dart:_http/http_impl.dart:363:9)
#1      _HttpClientRequest._onIncoming.<anonymous closure> (dart:_http/http_impl.dart:1082:55)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:204:14)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#13     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#14     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#15     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#16     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#17     _rootRun (dart:async/zone.dart:1120:38)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#21     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#22     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#23     _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#24     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#25     _StreamController.close (dart:async/stream_controller.dart:622:5)
#26     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#27     _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#28     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#29     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#36     _StreamController._add (dart:async/stream_controller.dart:640:7)
#37     _StreamController.add (dart:async/stream_controller.dart:586:5)
#38     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#44     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#45     _StreamController._add (dart:async/stream_controller.dart:640:7)
#46     _StreamController.add (dart:async/stream_controller.dart:586:5)
#47     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#48     _rootRun (dart:async/zone.dart:1120:38)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#51     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#52     _rootRun (dart:async/zone.dart:1124:13)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#55     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#56     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#57     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by anamarielzamora** [comment]
I think that HTTP in dart is expecting for a header to specify
```
'Content-type': 'application/json',
'Accept': 'application/json'
```
but I can not add headers in  -> s3client.listObjects() like in a normal http request

**Comment by knaeckeKami** [comment]
Can you show me how you construct your S3Client? (Without the secret + access keys). 
I don't think the headers are a problem, actually, S3 uses even XML, not JSON.

But I don't know why S3 would respond with a redirect.

**Comment by anamarielzamora** [comment]
```
    final region = "us-east-2";
    final AwsS3Client s3client = AwsS3Client(
    region: "us-east-2",
    bucket: "<bucketname>.s3.$region.amazonaws.com",
    accessKey: "access-key",
    secretKey: "secret-key"
```

**Comment by knaeckeKami** [comment]
Looks good.
does getObject() work? 

If yes, I would set a breakpoint on _HttpClientResponse.redirect to look into the response from AWS. I'm sorry to send you into this rabbit hole, but since I can't reproduce this issue I don't see a better way.
Do you know how to do that?
You should be able to see the status code, reasonPhrase, etc. in the variables when debugging. If you need assistance, just let me know.
When we have that, we can probably identify the issue.

**Comment by anamarielzamora** [comment]
No, getObject is not working, has the same error

**Comment by knaeckeKami** [comment]
Ok, can you set a breakpoint  _HttpClientResponse.redirect and look at the response?

**Comment by anamarielzamora** [comment]
How can i do that?

**Comment by knaeckeKami** [comment]
Do you use Android Studio?
On Android Studio, press "Shift" two times to open the "Find File" Window, search for 
"http_impl.dart", open this file.
In this file, search for "Response has no Location header for redirect" and set a breakpoint somewhere there.
Then, run your code in debug mode. When you do the request, it should break in the _HttpClientResponse class and you should see the status code, the message from S3 among other things in the Variables tab.

You could also try to do these requests via other ways, e.q. using the AWS CLI and see if it works that way. 

I suspect Amazon is sending a 301 Status code for some reason. If this is the case, look at https://stackoverflow.com/questions/13691881/301-moved-permanently-after-s3-uploading

**Comment by anamarielzamora** [comment]
Yes, you are right my status code is 301 let me check that page.

**Comment by knaeckeKami** [comment]
Are you sure that the region is right?

**Comment by anamarielzamora** [comment]
You are completely right, my mistake!

Sorry and thank you a lot for your time. It is the wrong region, I do not why I set another. Now I have the correct response

**Comment by knaeckeKami** [comment]
Great! I completely understand why you struggled, it's weird that the http client throws such a weird message with no additional information.
